export const USER_TAG = 'USER_TAG';
export const RESTAURANT_BRANCH_TAG = 'RESTAURANT_BRANCH_TAG';
export const MENU_ITEMS_TAG = 'MENU_ITEMS_TAG';
export const MODIFICATION_GROUP_TAG = 'MODIFICATION_GROUP_TAG';
export const INVENTORY_COUNT = 'INVENTORY_COUNT';
export const INVENTORY_COUNTS = 'INVENTORY_COUNTS';

export const FRY_STATION = 'FRY_STATION';
export const FRY_STATION_ITEM = 'FRY_STATION_ITEM';
export const FRY_STATION_ITEMS = 'FRY_STATION_ITEMS';
export const FRY_STATION_ITEM_MAPPING = 'FRY_STATION_ITEM_MAPPING';
export const FRY_STATION_ITEM_MAPPINGS = 'FRY_STATION_ITEM_MAPPINGS';
export const MENU_ITEM_V2 = 'MENU_ITEM_V2';
export const MENU_ITEMS_V2 = 'MENU_ITEMS_V2';
export const MODIFIER_ITEM_V2 = 'MODIFIER_ITEM_V2';
export const MODIFIER_ITEMS_V2 = 'MODIFIER_ITEMS_V2';
